[package]
name = "study"
version = "0.1.0"
authors = ["tianhhuan <q1436816322@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf="2.24.2"
protobuf-codegen-pure="2.25.0"
